server:
 port: 5002

spring:
 jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   generate-ddl: false
   hibernate:
     ddl-auto: none
   show-sql: true
   properties:
     hibernate:
       default_schema: cognizant_sc
       temp:
         use_jdbc_metadata_defaults: false
 datasource:
   driverClassName: org.postgresql.Driver
   url: jdbc:postgresql://revature-1808.cpb9nl533suc.us-east-1.rds.amazonaws.com:5432/postgres
   username: postgres
   password: IncomT-65
   initialization-mode: NEVER