server:
 port: 5002

spring:
 application:
   name: skill-cert-service
 jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   generate-ddl: false
   hibernate:
     ddl-auto: none
   show-sql: true
   properties:
     hibernate:
       default_schema: cognizant_sc
       temp:
         use_jdbc_metadata_defaults: false
 datasource:
   driverClassName: org.postgresql.Driver
   url: jdbc:postgresql://revature-1808.cpb9nl533suc.us-east-1.rds.amazonaws.com:5432/postgres
   username: postgres
   password: IncomT-65
   initialization-mode: NEVER
   
eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1