server:
  port: 8088

spring:
  application:
    name: project-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: cognizant_projects
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://revature.c5u4wo8rhlrm.us-east-2.rds.amazonaws.com:5432/revature
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:team1808}
    password: ${DB_PASSWORD:Bl4k3_&_tHe_fU11-staCk_Dev3lopeRs}



eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://10.226.195.57:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1

